### ISSUE TITLE
Music characters appear to be cut off from the top and bottom

### ISSUE THREAD

**Issue by tyrc94** [benwiggy/GoldenAge#2]
Using Finale 27 on Windows 10
When the font is loaded in Finale, the base of noteheads, accidentals, clefs and other music characters seem to be cut off
![image](https://user-images.githubusercontent.com/33178939/154859750-80cbd494-79fc-49f6-aca6-8014cf49b7f4.png)

I also loaded the font into Wordpad to check whether it was just a Finale issue, but the problem persists.
![image](https://user-images.githubusercontent.com/33178939/154859903-17d62699-2bed-48ce-a4dc-18057ad746c1.png)

Is this a Windows-specific issue with ascenders/descenders?

**Comment by benwiggy** [comment]
Thanks for this. I'm afraid I don't have access to a Windows machine, so I'll have to guess what the problem is.
I'll see what I can find out.

**Comment by benwiggy** [comment]
I've made a change to the bounding box values: can you see if this does anything?

**Comment by tyrc94** [comment]
No change I'm afraid
![image](https://user-images.githubusercontent.com/33178939/154864072-8030ee08-40af-4c59-a365-fed0faa4643a.png)

**Comment by tyrc94** [comment]
As an experiment I changed the Safe top and Safe bottom dimensions to the same as the BBox top and BBox bottom dimensions, and that seems to have resolved the problem:
![image](https://user-images.githubusercontent.com/33178939/154864996-2edf9eb7-9655-4c9e-8c28-ff6c607d6176.png)
Result in Finale:
![image](https://user-images.githubusercontent.com/33178939/154865009-289e709d-80cc-4f64-88c2-ff65984c994c.png)
The issue with those large dimensions is that text is very spaced out vertically:
![image](https://user-images.githubusercontent.com/33178939/154865058-5446a2c2-4a35-4264-a598-dfdf075cdd5b.png)

**Comment by benwiggy** [comment]
Hmm. It may be that I have to split the Text and Music bits into two separate fonts after all.

**Comment by benwiggy** [comment]
Can you try the latest version? Thanks.

**Comment by tyrc94** [comment]
This fix solves the problem with all but four of the characters. The characters (by their Unicode mapping) which are cut off slightly are:

- U+E053 (gClef8va) - the number is cut off partially
- U+E054 (gClef15ma) - the number is cut off entirely
- U+E24C (flag512thUp) - partial cut off from the top
- U+E24D (flag512thDown) - partial cut off from the bottom

I think these are the only characters that have an issue. 

Thanks for your efforts thus far, it is very much appreciated!

**Comment by benwiggy** [comment]
OK, I've tweaked the values a bit more, and issued a Release Version!! (Always the kiss of death. 🤣 )

**Comment by tyrc94** [comment]
Looks good to me, thanks!
