### ISSUE TITLE
Feature request: some templates or instructions

### ISSUE THREAD

**Issue by juanriccio** [benwiggy/GoldenAge#4]
Hello @benwiggy, thanks for this endeavor! I've been a fan of the GoldenAge font probably since Finale 2012.

Good to see it reborn in SMuFL form.
It would be great to have some basic templates, at least a lead sheet or piano sheet.
New users could then extend the basic templates for their needs, different instrumentation etc.,
but text/chords/notes/expressions etc would already be set from the start.

**Comment by benwiggy** [comment]
You're talking about Finale documents? That's beyond the scope of this project; but perhaps something for the Finale community to create.
